version: '5.0'

actions:
  # generate_dataset:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset.csv.gz

  generate_ctc_cases_tendinitis:
    run: ehrql:v1 generate-dataset analysis/ctc/ctc_definition_tendinitis.py --output output/ctc_data_cases_tendinitis.csv.gz
    outputs:
     highly_sensitive:
       dataset: output/ctc_data_cases_tendinitis.csv.gz

  generate_ctc_potential_control_tendinitis:
    run: ehrql:v1 generate-dataset analysis/ctc/ctc_definition_tendinitis_potential_ctrl.py --output output/ctc_data_potential_controls_tendinitis.csv.gz
    outputs:
     highly_sensitive:
       dataset: output/ctc_data_potential_controls_tendinitis.csv.gz

  matching round 1:
    needs: [generate_ctc_cases_tendinitis, generate_ctc_potential_control_tendinitis]
    run: >
      matching:v1.2.4
      --cases output/ctc_data_cases_tendinitis.csv.gz
      --controls output/ctc_data_potential_controls_tendinitis.csv.gz
    config:
      matches_per_case: 20
      match_variables:
        sex: category
      index_date_variable: index_date
      generate_match_index_date: no_offset
    outputs:
       highly_sensitive:
          matched_cases: output/matched_casesmatched_tendinitis.csv.gz
          matched_controls: output/matched_matches_tendinitis.csv.gz
          matched_combined: output/matched_combined_tendinitis.csv.gz
       moderately_sensitive:
          matching_report: output/matching_report_tendinitis.txt
     

  generate_ages_from_randomindex_dates:
    needs: [generate_ctc_potential_control_tendinitis]
    run: >
      python:v2 analysis/ctc/append_ctc_controls_index_date.py --output output/ctc_data_ptnl_controls_indexappended.csv.gz
    outputs:
     highly_sensitive:
       dataset: output/ctc_data_ptnl_controls_indexappended.csv.gz

  generate_ctc_controls_withrandom_indexdates:
    needs: [generate_ages_from_randomindex_dates]
    run: >
      ehrql:v1 generate-dataset analysis/ctc/2nd_extraction_controls.py --output output/ctc_data_potentialcontrols_withindexdates_andages_tendinitis.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/ctc_data_potentialcontrols_withindexdates_andages_tendinitis.csv.gz

# #measures - look at abx prescribing over time
#   generate_measure:
#     run: ehrql:v1 generate-measures analysis/measure_definition.py --output output/measures.csv 
#     needs: [generate_dataset]
#     outputs:
#       moderately_sensitive:
#         measure_csv: output/measures.csv

  
#   generate_report:
#      run: r:v2 analysis/abx_time_series.R
#      needs: [generate_measure]
#      outputs:
#       moderately_sensitive:
#         chart1: output/time_plot/abx_quarter_time_plot.png
#         chart2: output/time_plot/outcome_quarter_time_plot.png

#   generate_cohort:
#       run: r:v2 analysis/dataset_manipulate_cohort.R
#       needs: [generate_dataset]
#       outputs:
#         highly_sensitive:
#           chart1: output/dataset_formatted_cohort.csv
#           chart2: output/cohort/n_events.md
#           chart3: output/cohort/missingdata_count_df.md

#   run_model:
#     run: r:v2 analysis/iptw_coxph.R
#     needs: [generate_cohort]
#     outputs:
#       moderately_sensitive:
#         chart1:  output/cohort/age_spline_check.png
#         table1:  output/cohort/aictable_agespline.md
#         chart2:  output/cohort/imd_decile_rough_check.png
#         chart3:  output/cohort/n_hosp_appt_logoddsplot.png
#         chart4:  output/cohort/ps_density_plot.png
#         chart5 : output/cohort/ps_love_plot.png
#         table2:  output/cohort/n_events_tendinitis_complete_covariates_dataset.md
#         table3:  output/cohort/n_events_neuropathy_complete_covariates_dataset.md
#         chart6:  output/cohort/cox_models_tendinitis_and_neuropathy_forest.png
#         table 4:  output/cohort/all_cox_model_summaries.txt
#         table 5:  output/cohort/cumulative_cox_results.md
#         chart7:   output/cohort/km_tendinitis_combo_curve.png
#         chart8:   output/cohort/km_neuropathy_combo_curve.png

 